version: 0.2

env:
  variables:
    NEXT_PUBLIC_MST_WEBHOOK_URL: "https://your-real-webhook-url-here"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - rm -rf node_modules package-lock.json
      - npm ci
  build:
    commands:
      - npm run build || echo "No build step defined"
      - echo "Building and zipping the deployment package..."
      - aws s3 sync out/ s3://mstcpatx-s3-poc-bucket/ --delete
artifacts:
  files:
    - 'out/**/*'