version: 0.2

env:
  variables:
    NEXT_PUBLIC_MST_WEBHOOK_URL: "https://your-real-webhook-url-here"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - rm -rf node_modules
      - npm ci
  build:
    commands:
      - npm run build
      - npm run export
      - echo "Syncing static export to S3..."
      - aws s3 sync out/ s3://mstcpatx-s3-poc-bucket/ --delete
artifacts:
  files:
    - 'out/**/*'