version: 0.2

env:
  variables:
    NEXT_PUBLIC_MST_WEBHOOK_URL: "https://your-real-webhook-url-here"

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
      - npm run export
artifacts:
  files:
    - 'out/**/*'